### ISSUE TITLE
March Milestone TODO

### ISSUE THREAD

**Issue by edran** [ipab-rad/Youbot-RVO#13]
# Nantas
* [x] Add Laser node to code
* [x] Add AMCL Node
* [x] Initialise AMCL model and make class to fuse odometry and AMCL to be plugged in into the Tracker.
# Alex 
* [ ] TODO TODO list

**Comment by GreatAlexander** [comment]
Outdated/completed
